//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAdmissionSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string name { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public int pcm { get; set; }
        public int gujcet { get; set; }
        public double merit { get; set; }
    }
}
